apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginmicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LoginMicroservice
  template:
    metadata:
      labels:
        app: LoginMicroservice
    spec:
      containers:
      - name: loginmicroservice
        image: PMCNTR.azurecr.io/logindocker:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn1

---
apiVersion: v1
kind: Service
metadata:
  name: loginmicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: LoginMicroservice